name: Continuous Integration (CI)

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"

      - name: Build with Maven
        run: mvn clean package -DskipTests

  test:
    name: Test
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"

      - name: Install Google Chrome and ChromeDriver to e2e tests
        run: |
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i google-chrome-stable_current_amd64.deb
          sudo apt --fix-broken install -y

          CHROMEDRIVER_VERSION=$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE)
          curl -L -o chromedriver.zip https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip
          unzip chromedriver.zip
          chmod +x chromedriver
          sudo mv chromedriver /usr/local/bin/

      - name: Run application to e2e tests
        run: mvn spring-boot:run -Dspring-boot.run.profiles=test & sleep 60

      - name: Run tests
        run: mvn clean verify -Ptest

  qa:
    name: QA
    needs: test
    runs-on: self-hosted
    continue-on-error: true
    steps:
      - name: Quality Assurance with Sonarqube
        run: echo "Quality Assurance with Sonarqube"

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: qa

    steps:
      - name: Deploy
        run: echo "Deploy Application in Azure"








