name: Continuous Integration (CI)

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Package
    runs-on: ubuntu-latest
    steps:
      - name: Build and package
        run: echo "Build and package"

  test:
    name: Unit, integration and e2e tests
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Unit, integration and e2e tests
        run: echo "Unit, integration and e2e tests"

  qa:
    name: Quality Assurance with Sonarqube
    needs: test
    runs-on: self-hosted
    continue-on-error: true
    steps:
      - name: Quality Assurance with Sonarqube
        uses: echo "Quality Assurance with Sonarqube"

  deploy:
    name: Deploy Application in Azure
    runs-on: ubuntu-latest
    needs: qa

    steps:
      - name: Deploy
        uses: echo "Deploy Application in Azure"





