name: Continuous Integration (CI)

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Build and package
        run: echo "Build and package"

  test:
    name: Test
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Unit, integration and e2e tests
        run: echo "Unit, integration and e2e tests"

  qa:
    name: QA
    needs: test
    runs-on: self-hosted
    continue-on-error: true
    steps:
      - name: Quality Assurance with Sonarqube
        run: echo "Quality Assurance with Sonarqube"

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: qa

    steps:
      - name: Deploy
        run: echo "Deploy Application in Azure"





