name: Continuous Integration (CI)

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"

      - name: Build with Maven
        run: mvn clean package -DskipTests

  test:
    name: Test
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Unit, integration and e2e tests
        run: echo "Unit, integration and e2e tests"

  qa:
    name: QA
    needs: test
    runs-on: self-hosted
    continue-on-error: true
    steps:
      - name: Quality Assurance with Sonarqube
        run: echo "Quality Assurance with Sonarqube"

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: qa

    steps:
      - name: Deploy
        run: echo "Deploy Application in Azure"








